//
// Created by ayserjamshidi on 11/10/21.
//

#ifndef PROJECT_3_NETWORKED_SPELL_CHECKER_AYSERJAMSHIDI_ERRORS_H
#define PROJECT_3_NETWORKED_SPELL_CHECKER_AYSERJAMSHIDI_ERRORS_H

int DICTIONARY_FAILURE = 1,
	SOCK_CREATE_FAILURE = 2,
	LOGFILE_CREATE_FAILURE = 3,
	PORT_NOT_NUMBER = 4,
	PORT_OUT_OF_RANGE = 5,
	WORKERCOUNT_NOT_NUMBER = 6,
	WORKERCOUNT_OUT_OF_RANGE = 7,
	MAX_MSG_LENGTH_NOT_NUMBER = 8,
	MAX_MSG_LENGTH_OUT_OF_RANGE = 9,
	MODE_NOT_NUMBER = 10;

#endif //PROJECT_3_NETWORKED_SPELL_CHECKER_AYSERJAMSHIDI_ERRORS_H
